name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug GitHub Context
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Actor: $GITHUB_ACTOR"
        echo "Ref: $GITHUB_REF"

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::590519617819:role/github-actions-ecr-role
        aws-region: ap-south-1


    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build Docker Image
      run: |
        docker build \
          -t static-website \
          ./app


    - name: Tag Docker Image
      run: |
        docker tag \
          static-website:latest \
          590519617819.dkr.ecr.ap-south-1.amazonaws.com/static-website:latest


    - name: Push Docker Image to ECR
      run: |
        docker push \
          590519617819.dkr.ecr.ap-south-1.amazonaws.com/static-website:latest